development:
  t1:
    - accomodation
  t2:
    - debate_experience
    - tshirt_size

production:
  mmuopen:
    - tshirt_size
  uadc:
    - debate_experience
    - tshirt_size
  easters2013:
    - mobile
    - date_of_birth

test:
  t1:
    - accomodation
  t2:
    - debate_experience
    - tshirt_size
