development:
  mmuopen:
    - are_you_fasting
  t1:
    - accomodation
  t2:
    - debate_experience
    - tshirt_size
  utmaraaustrals2013:
    - are_you_fasting
production:
  mmuopen:
    - tshirt_size
  uadc:
    - debate_experience
    - tshirt_size
  easters2013:
    - mobile
    - date_of_birth
  utmaraaustrals2013:
    - are_you_fasting
  mmuopen:
    - are_you_fasting

test:
  t1:
    - accomodation
  t2:
    - debate_experience
    - tshirt_size
